name: Containerize AI4CI
on: repository_dispatch

jobs:
  build:
    name: Build and push image to Quay
    runs-on: ubuntu-20.04

    steps:
        - uses: actions/checkout@v1

        - name: login to quay
          run: docker login quay.io -p ${{ secrets.REGISTRY_PASSWORD }} -u ochatter

        - name: build docker image
          run: docker build -t explorer .

        - name: commit docker image
          run: docker tag explorer quay.io/ochatter/ai4ci

        - name: push committed docker image to quay.io
          run: docker push quay.io/ochatter/ai4ci:latest