

# This is a basic workflow to help you get started with Actions

name: Run Notebook NBConvert

# Controls when the workflow will run
on:

  repository_dispatch:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  weekly_update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
      GITHUB_ORG: ${{ secrets.GITHUB_ORG }}

      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      S3_ENDPOINT_URL: ${{ secrets.S3_ENDPOINT_URL }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      CEPH_BUCKET: ${{ secrets.CEPH_BUCKET }}
      CEPH_BUCKET_PREFIX: ${{ secrets.CEPH_BUCKET_PREFIX }}
      CEPH_KEY_ID: ${{ secrets.CEPH_KEY_ID }}
      CEPH_SECRET_KEY: ${{ secrets.CEPH_SECRET_KEY }}

      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: python -m pip install --upgrade pip -r requirements.txt
#       - name: Update data
#         run: python ./src/main.py
      - name: Data Collection notebook
        run: |
          python -m pip install jupyter nbconvert nbformat
          jupyter nbconvert --to notebook --execute 01_data_collection.ipynb --TemplateExporter.exclude_input=True --ExecutePreprocessor.kernel_name='python3' --output ../bls_notebook_executed
      - name: commit updated notebook
        uses: EndBug/add-and-commit@v7
        with:
          author_name: update notebook with pipeline
          message: "Update Notebook"
          add: "01_notebook_executed.ipynb"
